Release/1.0.0
Leo9Rdo/MyPokemons pull request #13
Opened 2024-06-29 23:53 UTC by Leo9Rdo

2024-06-30 12:31 UTC, pzinkevich42innowise requested changes

2024-06-30 12:31 UTC, pzinkevich42innowise commented on app/build.gradle
> +        }
убрать

2024-06-30 12:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/PokemonsObj.kt
> +data class pokemon(
PascalCase

2024-06-30 12:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/PokemonsObj.kt
> +    fun get_pokemon_by_id(id: Int): pokemon? {
camelCase

2024-06-30 12:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/PokemonsObj.kt
> +object pokemon_rep {
PascalCase

2024-06-30 12:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/PokemonsObj.kt
> +    val image_res: Int
camelCase

2024-06-30 12:31 UTC, pzinkevich42innowise commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintHorizontal_bias="1.0"
Можно без биаса?

2024-06-30 21:03 UTC, pzinkevich42innowise commented
Напрямую что ли фиксил сюда?

2024-06-30 21:06 UTC, pzinkevich42innowise requested changes

2024-06-30 21:06 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
> +    private val pokemonData = pokemons
зачем?

2024-06-30 21:06 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
> +        val newList = pokemons
в чём смысл?

2024-06-30 21:06 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/PokemonsObj.kt
> +    fun get_pokemon_by_id(id: Int): Pokemon? {
camelCase

2024-06-30 21:06 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/SecondActivity.kt
> +        intent?.let {
А если null ?

2024-06-30 21:06 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/rc/PokemonViewHolder.kt
> +    fun bind(pokemon: Pokemon, onClick: ((pokemon: Pokemon) -> Unit)?) {
А откуда тут взялся nullable?

2024-06-30 21:06 UTC, pzinkevich42innowise commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintHorizontal_bias="1.0"
???

2024-07-01 08:10 UTC, Leo9Rdo commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
> +    private val pokemonData = pokemons
сделал camelCase стиль написания. решил сразу везде исправить...или не стоило?

2024-07-04 10:33 UTC, pzinkevich42innowise requested changes

2024-07-04 10:33 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
> +    private val pokemonData = pokemons
В чём смысл этой переменной?

2024-07-06 12:38 UTC, pzinkevich42innowise approved these changes

2024-07-06 12:57 UTC, merged