Work with RV, Diff, Divider
Leo9Rdo/MyPokemons pull request #7
Opened 2024-06-22 23:46 UTC by Leo9Rdo

2024-06-23 20:31 UTC, pzinkevich42innowise requested changes

2024-06-23 20:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
> +        binding.recyclerView.layoutManager = LinearLayoutManager(this)
Можно было в XML

2024-06-23 20:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
> +//        }
зачем оставлять этот код в комментариях?

2024-06-23 20:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
> +        diffResult.dispatchUpdatesTo(adapter)
Почему не в адаптере?

2024-06-23 20:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
>      private var current_index = 0
Это ещё надо?

2024-06-23 20:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
>      private fun update() {
Это ещё надо?

2024-06-23 20:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/rc/PokemonListAdapter.kt
> +    inner class PokemonViewHolder(private val binding: ItemPokemonBinding) :
Два холдера, используется один. Его и оставь

2024-06-23 20:31 UTC, pzinkevich42innowise commented on app/src/main/res/layout/activity_main.xml
> +<!--        app:layout_constraintTop_toBottomOf="@id/recycler_view" />-->
Зачем оставлять этот код?

2024-06-23 20:31 UTC, pzinkevich42innowise commented on app/src/main/res/layout/item_bug_pokemon.xml
А зачем столько лейаутов одинаковых без применения?

2024-06-29 09:00 UTC, pzinkevich42innowise requested changes

2024-06-29 09:00 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
>      private fun update() {
я не вижу применения этой штуки

2024-06-29 09:00 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/rc/PokemonListAdapter.kt
> +    inner class PokemonViewHolder(private val binding: ItemPokemonBinding) :
всё равно два класса в проекте, когда используется один

2024-06-29 14:16 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
> +            val currentPokemon = pokemon_data.firstOrNull()
А в чём суть этих строк?

2024-06-29 14:17 UTC, pzinkevich42innowise requested changes

2024-06-29 14:17 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/rc/PokemonListAdapter.kt
> +    var onClick: ((pokemon: pokemon) -> Unit)? = null
```suggestion
    var onClick: ((pokemon: Pokemon) -> Unit) = { }
```

2024-06-29 14:37 UTC, Leo9Rdo commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
> +            val currentPokemon = pokemon_data.firstOrNull()
ты мне помечал строку с объявлением переменной current_index. Я её убрал и отредачил. Теперь по клику будет возвращать элемент из списка, если он имеется.

2024-06-29 14:54 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
> +            val currentPokemon = pokemon_data.firstOrNull()
ну так у тебя переход по первому покемону всегда будет, разве нет?

2024-06-29 15:02 UTC, Leo9Rdo commented on app/src/main/java/com/example/mypokemons/MainActivity.kt
> +            val currentPokemon = pokemon_data.firstOrNull()
Всё гуд воркает

2024-06-29 15:22 UTC, pzinkevich42innowise approved these changes

2024-06-29 15:24 UTC, merged